services:
  - type: web
    name: theo-inventory-management
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: SECRET_KEY
        value: theo-inventory-super-secret-key-2024-production
      - key: FIREBASE_PROJECT_ID
        value: inventory-3098f
      - key: FIREBASE_STORAGE_BUCKET
        value: inventory-3098f-p2f4t
      - key: FIREBASE_TYPE
        value: service_account
      - key: FIREBASE_PRIVATE_KEY_ID
        value: 082b0b0a404cbca36c1007495be79eb63d83846d
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCw6InUY5GRls5w\nTKO8pTHjaF7slmRPnNv66OHCePHNClmOVPN/i1JdcNp93Uby7v3ZVPXwo+Ar89ad\n4p/fmqb7qL86sb+tFQNVpuQ3456frclVh6/HAXkEtIaOve+Qs+cGH1Fl7rctbpsL\nFe3vcOtc5vA8doQc1Avt9VFQfVySrPykgfkYmoY4mSM0mwECgeU3fhtob1+5Hisc\nXAffrKZvOq5Ny92zY9IlM7c5nA65JDCQQDJkV12XNYqLRIoWTIzgO3E0u3wrpgfB\nLQhSAO+eu0/Xt7KMcJdOGv+NGrYzALv248DzGsApu4jVweRd9pEMnbQUW2HxLN80\nfSiOelrVAgMBAAECggEAEIV/DcNIvoCHggxeRElnOdYu+0hmUNsU3j9uihNyfZQo\nXfcIEJLJ2+kktpl6PUjdkzTwjQs47dHlarRV+vN+AcW2KjycaoUqXQ7rhF6xGzeH\nNIIqA9ta2nojkOQjIe/zNOqq1uqu18LbHvNq17BDgtcce4EUAH87J/t/nxU+FoKC\ndDCOJfui+cPVQ+XsJ34Wyww/1mhyelfCVH8+m41ss7zJtzOqZT2cCexYvC033W95\nMNfTWMWLZOsDpvSqQ1Vi6J743a57BG2j4ZGkIRYQ2LkGtF4s+zrBJbNgH7EmE2Wg\nPKeSPXJXAtmy41JFoD1caHLUWk1xnrfy6dZl9upuNwKBgQDj1Jq6pU83Qlc5ys2k\nwqdx4mw7SUohnstmAqGOTgtXCzUqEa/oJgfL9Rm5TuODChsLY2hOkdO34X2a3y55\n9gT6AziN6ezlSXDbaFE9OWg+2o5zGfAGwvJx6w3B44Lw9R4xQnL4FB+F7T+pC7Ee\nlpkKVtVE+EAeC4VTbCq03djfawKBgQDGyB+HSjVfQe4MTtZJw/6TqJiKiaqBztuu\nplizYby83XyOoRATi7pfl0rsI7uI1UWkZgpjPj5KslWZTSsSXSbq+InHg0zgay7y\n88M7mapSv7SCVmO2L1oIrL/Tu9FgH7gvzcZNu40EGsijE7yJMUAC5sCEJKBxy4fm\nDahZ6V9+vwKBgGiIxi3ZZ41dPRRhPxXX0mhokWxqZj8i0wSNNH9Mw9s+YzhYQTPt\nLyqf3RuvXKhlXJ9PDy7trgzyw2Tp/jMrdIEaNTq4GF/j4IprRMsoqfIc6btaLU2M\n6Rzn0rohn5TbguzrJkE5SnVytADmQnBcfP/Hc7dfiFvAwX3TZYzzNWzdAoGBAIGL\nbjCnBf1cZByVTEWqe0ATgcXXTc1m1/gL5IaSzYNv/HqfMHDsgLtHR8Z4ywCzrL0k\n2uQubj4T1oEfr1A6cOB0tKXXRcSDVYdzoOo4jK18zdCbKERUu6InoqQEJME2KrzM\np82EyrPAGL1eYWIvPH4nj5MOo5lFgP1GLU7bLibVAoGBAK81doK6oviNmxBru7Un\nBLJlBMfiC2v6zG/bYo50rfFqpKyiPNDTHnA1RGxjNJ852Bw510vlisdlZf40cFHI\nznf5uqg0CnuHTtD0/XPbPq8J79jFbVTKyUkpMAfcgcypH6uurAV57i/hmxo02huk\n/b+0VHYnv1jNhLZyVAUk60ku\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@inventory-3098f.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: "107138131050410819327"
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_CLIENT_X509_CERT_URL
        value: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40inventory-3098f.iam.gserviceaccount.com
      - key: FIREBASE_UNIVERSE_DOMAIN
        value: googleapis.com
